name: Update Node Positions
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Node Info"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.repository.name == 'Cloudflare-Data-Center-IATA-Code-list' &&
      (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Full Data with Geo Positions
        run: |
          python generate_full_data.py

      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"

          git add ./cloudflare-iata-full*.json

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes detected in the geo position files"
            exit 0
          else
            echo "Changes detected, committing"
            git commit -m "chore: update node geo positions on $(date +'%Y-%m-%d')"
            git push origin $CURRENT_BRANCH
          fi